### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by ReiberAndras** [slackr31337/PorcupinePipeline#21]
Hi!

I get a ConnectionResetError: Cannot write to closing transport error message when I pronounce the wake word and approximately 1 minute of inactivity elapsed after the last tts response  was received. I believe this is because of the websocket has been closed. 

I am using windows 11.  Here is the stacktrace:

```
2023-07-20 23:51:01,355  INFO Waiting for wake word to trigger audio
2023-07-20 23:52:44,837  INFO Detected keyword `alexa`
2023-07-20 23:52:45,016  INFO Listening and sending audio to voice pipeline
Traceback (most recent call last):
  File "c:\Users\User\projects\PorcupinePipeline-main\voice_pipeline.py", line 489, in <module>
    asyncio.run(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\User\projects\PorcupinePipeline-main\voice_pipeline.py", line 136, in main
    await loop_pipeline(state)
  File "c:\Users\User\projects\PorcupinePipeline-main\voice_pipeline.py", line 236, in loop_pipeline
    await websocket.send_json(pipeline_args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_ws.py", line 165, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_ws.py", line 151, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\http_websocket.py", line 690, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by slackr31337** [comment]
Hi [ReiberAndras](https://github.com/ReiberAndras),

Looks like a websocket keep-alive has to be added to this code. I will work on that soon.


Robert

**Comment by slackr31337** [comment]
Hi ReiberAndras,

I just pushed some changes to address this issue. When you get a chance, can you test it out? 

Robert

**Comment by ReiberAndras** [comment]
Hi @slackr31337 

The issue seems to be solved. I no longer receive the error message. Thank you.
